---
req_pack:
  - "python-apt"
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "software-properties-common"
docker_install_docker_compose: True
docker_compose_version: "1.21.0"
docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
